import type { Metadata } from "next";
import { Inter, Cinzel_Decorative, Cairo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { NextIntlClientProvider } from "next-intl";
import Footer from "@/components/Footer";
import { unstable_setRequestLocale } from "next-intl/server";
import { LOCALES } from "@/constants";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});
const cairo = Cairo({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-cairo",
});

const cinzel = Cinzel_Decorative({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-cinzel",
});

export const metadata: Metadata = {
  title: "Mosque",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = (await import(`@/../messages/${locale}.json`)).default;
  unstable_setRequestLocale(locale);
  return (
    <html lang={locale}>
      <body
        className={`${inter.variable} ${cinzel.variable} ${cairo.variable} font-inter`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Navbar />
          <Toaster />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

export function generateStaticParams() {
  return LOCALES.map((locale) => ({ locale }));
}
